[package]
name = "balavr"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { version = "0.8.0", package = "libadwaita", features = ["v1_5"] }
chrono = { version = "0.4.42", features = ["clock"] }
gtk = { version = "0.10.0", package = "gtk4" }
gtk4-layer-shell = "0.6.3"
hyprland = "0.3.13"
tokio = { version = "1.47.1", features = ["full"] }
zbus = "5.11.0"
